baseURL = "https://dubst3pp4.github.io"
languageCode = "en-us"
theme = "beautifulhugo"
googleAnalytics = "UA-107193689-1"
title = "dubst3pp4"
[Author]
github = "dubst3pp4"
googleplus = "+MarcHanisch"
name = "Marc Hanisch"
reddit = "dubst3pp4"
twitter = "dubst3pp4"
[[menu.main]]
name = "Tags"
url = "tags"
weight = 3
[[menu.main]]
name = "Blog"
url = ""
weight = 1
[params]
comments = true
dateformat = "January 2, 2006"
logo = "img/dubst3pp4-avatar.png"
rss = true
subtitle = "random bits"
