---
label: default
hide_body: false
is_partial: false
fields:
- type: text
  label: Title
  name: title
- type: textarea
  name: description
  label: Description
  description: A short description of the content
- type: datetime
  name: date
  label: Date
- type: tag_list
  name: tags
  label: Tags
pages:
- content/imprint.md
- content/post/test.md
