---
pages:
- post/test.md
hide_body: false
fields:
- type: text
  label: Title
  name: title
- type: textarea
  name: description
  label: Description
  description: A short description of the content
- type: datetime
  name: date
  label: Date
- type: tag_list
  name: tags
  label: Tags
- type: field_group_list
  config:
    labelField: 
  label: Keywords
  name: keywords
  fields:
  - type: text
    name: keywords
    label: Keywords
